# Generated by Django 5.0 on 2023-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="verification_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_verified_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
