# Generated by Django 4.2.7 on 2023-11-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_code', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('violation', models.CharField(choices=[('紅線停車', '紅線停車'), ('黃線臨車', '黃線臨車'), ('行駛人行道', '行駛人行道'), ('未停讓行人', '未停讓行人'), ('切換車道未打方向燈', '切換車道未打方向燈'), ('人行道騎樓停車', '人行道騎樓停車'), ('闖紅燈', '闖紅燈'), ('逼車', '逼車'), ('未禮讓直行車', '未禮讓直行車'), ('未依標線行駛', '未依標線行駛'), ('其他', '其他')], max_length=100)),
                ('status', models.CharField(choices=[('通過', '通過'), ('未通過', '未通過'), ('其他', '其他')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('traffic_violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.trafficviolation')),
            ],
        ),
    ]
