# Generated by Django 5.0 on 2023-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_auto_20231213_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficviolation",
            name="officer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
