# Generated by Django 5.0 on 2023-12-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_trafficviolation_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="traffic_violation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.trafficviolation",
            ),
        ),
        migrations.AlterField(
            model_name="trafficviolation",
            name="officer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
