name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Install dependencies
        run: |
          gcloud components install app-engine-python
          gcloud components install app-engine-python-extras

      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --project *** --quiet
