name: py_lint

on:
  push:
    branches:
      - master
      - workflows

jobs:
  py_lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Lint
        run: | 
          pip install pylint
          python -m pylint . --output-format=colorized --output-file=lint.out
