name: pylint

on:
  push:
    branches:
      - master
      - workflows

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Tests
        run: |
          python manage.py test

      - name: Lint
        run: | 
          pip install pylint-django
          pylint --load-plugins pylint_django --django-settings-module=TrafficViolationReport.settings templates/*
